#!/bin/bash
if [ "$EUID" -eq 0 ]; then
    echo "Restarting network manager..."
    systemctl restart network-manager
    sleep 1s
    echo "Releasing DHCP..."
    dhclient -r
    sleep 1s
    echo "Renewing DHCP..."
    dhclient -1
    sleep 1s
else
    echo "You must be root"
fi
